### ISSUE TITLE
[Bug] start application

### ISSUE THREAD

**Issue by renat473** [storybookjs/status-page#30]
when starting the application this error occurs
and the first build

`Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at index.tsx:61.
    at StatusPage (webpack-internal:///./pages/index.tsx:83:3)
    at WithSuperJSON (C:\Users\Admin\Desktop\status-page\node_modules\babel-plugin-superjson-next\dist\tools.js:115:55)
    at MyApp (webpack-internal:///./pages/_app.tsx:26:3)
    at StyleRegistry (C:\Users\Admin\Desktop\status-page\node_modules\styled-jsx\dist\index\index.js:449:36)
    at PathnameContextProviderAdapter (C:\Users\Admin\Desktop\status-page\node_modules\next\dist\shared\lib\router\adapters.js:60:11)
    at AppContainer (C:\Users\Admin\Desktop\status-page\node_modules\next\dist\server\render.js:289:29)
    at AppContainerWithIsomorphicFiberStructure (C:\Users\Admin\Desktop\status-page\node_modules\next\dist\server\render.js:325:57)
    at div
    at Body (C:\Users\Admin\Desktop\status-page\node_modules\next\dist\server\render.js:612:21)
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at renderElement (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6043:9)
    at renderNodeDestructiveImpl (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
error - Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at renderElement (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6043:9)
    at renderNodeDestructiveImpl (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (C:\Users\Admin\Desktop\status-page\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5) {
  page: '/'
}
`

**Comment by yannbf** [comment]
I believe this issue has been fixed, feel free to reopen if that's not the case!
